voormedia/rails-erd

rails-erd.gemspec

I was trying to determine the licenses for my dependencies. I found that the RubyGems API will return the license, but only if it is specified in your gemspec file.

Add license to gemspec

---

lib/rails_erd/cli.rb
lib/rails_erd/config.rb
lib/rails_erd/diagram.rb
test/support_files/erdconfig.exclude.example
test/unit/config_test.rb
test/unit/diagram_test.rb

Fixes #50  handles only, and exclude as strings, properly parse config, and ensure we don't swap from symbol to string and back.

Parse Exclude and Only options into array, Process as Strings. 

---

README.md
examples/erdconfig.example
lib/rails_erd.rb
lib/rails_erd/cli.rb
lib/rails_erd/domain/attribute.rb
lib/rails_erd/domain/entity.rb
test/unit/attribute_test.rb

This is a rewrite of #83. @eagleas did solid work, and since we added configuration options, I thought I'd rework their code to take advantage of the need to at least rebase #83 and make sure PK sorting was a selectable option. 
This also adds marking primary, unique, and foreign keys as such on the diagram; if anyone thinks this should be a command-line option, it should be trivial to add, and would make a nice beginner/new-to-the-project PR.

Mark primary and unique keys, add PK sorting option

---

lib/rails_erd/domain/relationship.rb

With this test, the task (in #46) doesn't fail.

Checks that a model is not abstract before all 

---

examples/identity.rb
lib/rails_erd/domain/relationship.rb
test/test_helper.rb

== lib/rails_erd/domain/relationship.rb ==
W: 73:  9: end at 73, 8 is not aligned with unless at 66, 56
== examples/identity.rb ==
W: 36:  5: Useless assignment to variable - macro.
W: 45:  5: Useless assignment to variable - macro.
== test/test_helper.rb ==
W: 37: 20: Ambiguous splat operator. Parenthesize the method arguments if it's surely a splat operator, or add a whitespace to the right of the * if it should be a multiplication.

Fix some rubocop warnings

---

lib/rails_erd/diagram/graphviz.rb
test/unit/graphviz_test.rb

This is a bit of an experiment. As I was looking into JRuby test failures this morning, I was having trouble getting JRuby to play nice with filenames with spaces, and I really wonder how much we need this (especially if its causing xRuby problems). Mostly I'm filing this to see if anyone cares, and if TravisCI feels any happier.
Comments welcome.

Drop support for spaces in output filenames

---

lib/rails_erd/domain/attribute.rb
test/unit/attribute_test.rb

Index + swap should be a lot faster than delete + unshift. Delete has to scan the whole array until it finds the object to delete, and the same goes for detect, so it does more work than nedeed.
I also changed the related test because it wasn't really testing anything, I commented the whole prepend_primary code and the test still passed because the primary key "id" is already first (original order).

Improve Attribute#from_model

---

lib/rails_erd/tasks.rake
test/unit/rake_task_test.rb

The original issue #42 doesn't specifically states whether the problem
happens by using the rake task or CLI, but while the CLI is fixed by
later changes, the rake task is still broken. It tries to compare model
names that comes in an array of symbols via
`options.only`/`options.exclude` against String model names.
This keeps both CLIs (rake and binary) consistent in handling
comma-separated values. The binary CLI splits into an array of strings,
which the rake task should too.

Fix #42 for rake tasks

---

lib/rails_erd/diagram.rb
test/unit/diagram_test.rb

Error "No entities found; create your models first!" occurred when using a 'only' or 'exclude' filter.
options.only/options.exclude contains an array of symbols and not strings.

Fixed 'No entities found' error when using filter

---

lib/rails_erd/domain/attribute.rb

When you are using PostGIS geometry column types such as st_point:
```
create_table "businesses", force: :cascade do |t|
t.geometry "latlng",     limit: {:srid=>0, :type=>"point"}
t.string   "phone",                                         null: false
t.datetime "created_at",                                    null: false
t.datetime "updated_at",                                    null: false
end
```
Running `rake erd` fails with the following error:
```
TypeError: no implicit conversion of Symbol into Integer
/Users/yosriady/.rvm/gems/ruby-2.2.0/gems/rails-erd-1.4.1/lib/rails_erd/domain/attribute.rb:133:in `[]'
/Users/yosriady/.rvm/gems/ruby-2.2.0/gems/rails-erd-1.4.1/lib/rails_erd/domain/attribute.rb:133:in `limit'
/Users/yosriady/.rvm/gems/ruby-2.2.0/gems/rails-erd-1.4.1/lib/rails_erd/d …
```

Fix limit for PostGIS geometry column types

---

lib/generators/erd/USAGE
lib/generators/erd/install_generator.rb
lib/generators/erd/templates/auto_generate_diagram.rake
lib/tasks/auto_generate_diagram.rake

Hey @kerrizor 
I'm following your advice. I put that quickly through, on the model of the annotate_models gem.
with an install generator you pull a stupid rake task that loads the erd rake tasks. And the rake task I created plugs itself on the db:migrate and co tasks
I must say I have not tested that in the context of the gem cause I really can't spend the time right now but if you are willing to spend 1 hour, it should not be too hard to have it working (hopefully it does already)
Cheers
Greg

Auto generate diagram on db:migrate

---

lib/rails_erd/domain/attribute.rb

This PR will return nil in the `limit` method of `rails_erd/domain/attribute.rb` -- this problem was causing a crash with our models, and this fixes that.
Feel free to take it or leave it -- I'll be using my own hacked-up version for now either way. Let me know if I can help with this any more.

return nil if native_type is geography

---

README.md
examples/erdconfig.another_example
examples/erdconfig.example
lib/rails_erd/cli.rb
lib/rails_erd/diagram.rb
lib/rails_erd/domain/attribute.rb
test/support_files/erdconfig.example
test/support_files/erdconfig.exclude.example
test/unit/config_test.rb
test/unit/diagram_test.rb

- false is now an acceptable option for attribute
```bundle exec erd --attributes=false```
- test false functionality
- update config tests to recognize false as a possible argument for attribute
- false listed as acceptable in documentation
paired with @theutahkate @cherimarie

Resolves issue #137 Attribute = False

---

lib/rails_erd/cli.rb

When working on a large project that had legacy code in lib/ where
classes were inheriting from from Base or from ActiveRecord::Base but
instead were `class Foo < Struct.new` (a bad pattern) `eager_load!`s
behavior was causing classes to be reinstantiated and thus, due to the
behavior of `Struct.new` creating a new anonymous class with each call,
resulting in a TypeError. This will save us from those, at least.

Rescue from TypeError when loading target app

---

lib/generators/erd/templates/auto_generate_diagram.rake
lib/rails_erd.rb
lib/rails_erd/engine.rb

Reverts voormedia/rails-erd#176
The autogeneration needs a feature flipping environmental/config option. Until we get that, disabling.

Revert "make RailsERD Engine"

---

CHANGES.md
lib/rails_erd/version.rb

* Revert auto-generation of diagrams added in #176 (#191)
* Fix some Ruby warnings (#187)
* Rescue from TypeError when loading target app (#185)

Bump version number to 1.4.6 for release

---

lib/rails_erd/diagram/graphviz.rb
test/unit/graphviz_test.rb

I had in my configuration file the option horizontal but was giving me vertical graphs and viceversa. I'm attaching all my files.
[erd.pdf](https://github.com/voormedia/rails-erd/files/86785/erd.pdf)
[erdconfig.txt](https://github.com/voormedia/rails-erd/files/86786/erdconfig.txt)

Fixed horizontally graph when vertical was wanted and viceversa

---

lib/rails_erd/domain/relationship.rb

identifier could be a symbol which led to double association_identies
fixes #70

fix grouping of associations

---

customise.html

Current documentation states "indirect" as an option, whereas the available option is called "direct"

Updated diagram options (indirect -> direct)

---

test/unit/attribute_test.rb
test/unit/graphviz_test.rb

Undef some methods before redefining, fixes a number of warnings when running the tests.

Avoid warnings when redefining methods in tests.

---

README.md

After many years I've used this gem with a Rails 5 project, and it works just fine! Except for some minor issues for which I've opened pull requests.
Thanks @kerrizor for your awesome working maintaining this gem!

Mention Rails 5 in README

---

lib/rails_erd/domain/specialization.rb
test/unit/attribute_test.rb
test/unit/domain_test.rb
test/unit/graphviz_test.rb

The specialisation edge is added twice if an STI base class inherits from an abstract class. For example:
`ApplicationRecord (abstract) -> Beverage (STI base) -> Beer -> (STI child)` causes the `Beverage -> Beer` specialisation to occur twice. This causes Graphviz to fail in confusion with the message:
> Error: in routesplines, cannot find NORMAL edge
This became a bigger issue with Rails 5, because the abstract base class `ApplicationRecord` is added by default.

Avoid duplicate specializations when using STI with an abstract base class

---

README.md
test/unit/graphviz_test.rb
test/unit/rake_task_test.rb

`File.exists?` apparently was deprecated as of Ruby 2.1.

Fix deprecation of File.exists?

---

lib/rails_erd/cli.rb

Fixes #114 
I wanted to run ` bundle exec erd` on our Sinatra apps, with this patch all I had to do was create a `config/environment.rb` file that loaded my application environment (specially models) and the ERD output was successfully generated.
Thanks guys for the awesome project! 👍

Add supports to non Rails apps.

---

README.md
examples/erdconfig.example
lib/rails_erd.rb
lib/rails_erd/cli.rb
lib/rails_erd/config.rb
lib/rails_erd/diagram/graphviz.rb
lib/rails_erd/domain/entity.rb

Resolves issue #156 
Enabling clustering will create subgraphs in graphviz. Clustering is based on the topmost namespace/module name.
With clustering enabled all Recipe::* models will all be sorted into a 'Recipe' cluster.
Please note, that this simply a made up example and not production app.
Without clustering:
With clustering:

Implement clustering by namespace

---

CHANGES.md
lib/rails_erd/version.rb

Lots of new stuff in 1.5.0! We've gotten Rails 5.x support in place, as
well as adding 2 new options. "clustering" will draw a box around models
contained in the same name space, helping to visually organize areas of
concern. "only_models_include_depth" - although awkwardly named - will
restrict the depth of graphing to the supplied value.
* New option of 'clustering' by namespace (#205)
* Support for 'only_models_include_depth' option (#219)
* Added basic support for non-Rails apps (#208)
* Avoid duplicate specializations when using STI with an abstract base class (#211)
* Fixed Ruby 2.1 deprecation warnings (#209)
* Fixes to tests (#210, #213)
* Various documentation fixes (#203, #212)

Release 1.5.0

---

Gemfile.lock

When installing the json gem with ruby 2.2.x, compilation fails. The
details of why it is failing are in this[0] github issue. Subsequent gem
releases (1.8.2+) have fixed the issue, so this commit bumps the gem to
the latest non-broken version so that people with ruby 2.2.x can install
and run the gh-pages for rails-erd locally.
[0] - https://github.com/flori/json/issues/229

Bump json gem to 1.8.3 so that gh-pages can be generated with ruby 2.2.x

---

customise.html

Brevity is the soul of wit and so too should our documentation be (at
least, in this case as it is just downright misleading).

Remove old 1.0 warning message as we're on 1.5 by now

---

lib/rails_erd/domain/entity.rb

This small change allows this gem to run with rubies prior to 2.3.

remove dependency on ruby 2.3

---

README.md
_includes/navigation.html
_layouts/default.html
customise.html
gallery.html
install.html

The link at the top of the repository can also be updated to HTTPS but I have no control over that.

Update GitHub pages links to HTTPS

---

lib/rails_erd/tasks.rake

This adds an "erb:check_depencencies" rake task verify GraphViz is installed. If it isn't, the user is given a link to the installation instructions on the website.

Add erd:check_dependencies rake task to verify GraphViz is installed

---

README.md
lib/rails_erd/cli.rb
lib/rails_erd/diagram/graphviz.rb
test/unit/graphviz_test.rb

I've allowed the user to specify the splines type in options. I did this so I could set it to "ortho" as I think it's quite neat. Attribute reference here: http://www.graphviz.org/doc/info/attrs.html#d:splines.
On another note, I wanted to be able to have a vertical node layout (i.e. heading at the top and attributes underneath) without changing the rank direction of the overall graph but couldn't find a neat solution. Any suggestions?
Thanks

Allow user to specify splines type in options

---

.travis.yml
README.md
gemfiles/Gemfile-rails.5.0.x
test/test_helper.rb
test/unit/attribute_test.rb
test/unit/domain_test.rb
test/unit/graphviz_test.rb
test/unit/rake_task_test.rb

This adds Rails 5.0.x to the test matrix and resolves the warnings when running against that version range (currently 5.0.2). Note that this does not fix the warnings in #249 (shown at https://travis-ci.org/voormedia/rails-erd/jobs/151324467).
These are the warnings that are resolved:
```
/home/rails/rails-erd/test/unit/domain_test.rb:228: warning: ambiguous first argument; put parentheses or a space even after `/' operator
```
```
Use assert_nil if expecting nil from /home/rails/rails-erd/test/unit/attribute_test.rb:277:in `block in <class:AttributeTest>'. This will fail in MT6.
```
```
DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead. (called from …
```

Fix warnings when running tests against Rails 5.0.x

---

.gitignore
lib/rails_erd/diagram.rb

I noted the `only` flag was not being respected.
This was because `.only` is a method inherited from `Hash` on `ActiveSupport::OrderedOptions` therefore it was always returning an empty `{}`.
A long term solution may be to change the option name to avoid using a loaded term, this fix simply changes the access method to use the traditional `Hash` accessor `[]`

Fix only flag to work 

---

README.md
lib/generators/erd/templates/auto_generate_diagram.rake
lib/rails_erd.rb

#162 
I fixed auto diagram generation function in accordance with #162.

Fix auto diagram generation

---

lib/rails_erd/diagram/templates/node.html.erb
lib/rails_erd/diagram/templates/node.record.erb
test/unit/graphviz_test.rb

Four tests where forgotten in PR #183, where the meaning of the horizontal and vertical orientation options where swapped. Inverting the tests uncovered that one test, `"node record labels should not have direction reversing braces for horizontal orientation"`, did not actually test what it says because the regular expression used had an issue. 
The pipe character, when not escaped, is used in regular expressions to enumerate alternatives. The regex `/cat|dog/` matches both the string `"cat"` as well as the string `"dog"`.
The regex with the unescaped pipe character in the test `"node record labels should not have direction reversing braces for horizontal orientation"` matches any string that ends with a double quotation mark `"` and does not actually test whether the test input contains …

Fix inner layout orientation in record templates

---

lib/rails_erd/cli.rb
lib/rails_erd/tasks.rake
test/unit/rake_task_test.rb

Working off of #233 which attempted to solve #3 once and for all.. tests on #233 were failing due to undefined `config` method on Rails app being manually built in test. That's not a great situation, but adding a couple guard clauses fixes the issue neatly enough.

eager load all the things to include models provided by engines take 2

---

CHANGES.md
lib/rails_erd/version.rb
rails-erd.gemspec

Another big point release!
* Improved < Ruby 2.3 support (#239)
* Squashed once and for all the horizontal vs vertical orientation bugs (#241)
* Added option for specifying spline types (#242)
* Added a check for Graphviz installation before building out object graph (#248)
* Fixed a bug in auto-generation rake task (#252)
* `--cluster` option will work more reliably now! (#253)
* Because it is 2017, we added Rails 5 to our official test matrix (#254)
* Fixed a bug in `--only` that prevented it from working reliably (#257)
* Added eager loading across all namespaces in the app (#258)
* Minor improvements to tests (#228)

Release v1.5.1

---

gallery.html

This PR removes one reference to "Rails 3" from a page in the explanatory site.

Gallery: Drop the 3 from Rails 3

---

install.html

This PR updates the docs site to not say "Rails 3" so very often.
- In cases where version is important "3+" has been kept, as a note.

Install page: Rails 3 references updated to reflect "3+"

---

README.md

I fix a documentation as follows.
- Fix erd install command documentation for #283
- Fix macOS expression. ('M'acOS -> 'm'acOS)
- refs: https://www.apple.com/macos/high-sierra/

Fix documentation for #283

---

Gemfile
gemfiles/Gemfile-rails.3.2.x
gemfiles/Gemfile-rails.4.1.x
gemfiles/Gemfile-rails.4.2.x
gemfiles/Gemfile-rails.5.0.x

I got back into the project this morning and noticed a TON of test
failures in recent PRs. 5 min of research led me to these issues in
recent versions of minitest and Rails. Since we use a variety of Rails
versions, pinning the version minitest to one that works across legacy
Rails versions is a solution for today, but we may have to take a look
at a more sophisticated solution in the future.
seattlerb/minitest#730
rails/rails#31624

Pin minitest to 5.10.1

---

lib/rails_erd/domain/entity.rb

Here's a fix for a trivial Ruby warning.
FYI following is a quick step to reproduce the warning.
`% ruby -rrails-erd -we "require 'rails_erd/domain/entity'"`

⚠ ambiguous first argument; put parentheses or a space even after `/' operator

---

gemfiles/Gemfile-rails.3.2.x
gemfiles/Gemfile-rails.4.0.x
gemfiles/Gemfile-rails.4.1.x
gemfiles/Gemfile-rails.4.2.x
gemfiles/Gemfile-rails.5.0.x
lib/rails_erd/tasks.rake
test/unit/rake_task_test.rb

Rebasing PR #266

---

lib/rails_erd/diagram/graphviz.rb

This PR suppresses the following warnings.
```console
bundle exec rake
/Users/koic/src/github.com/voormedia/rails-erd/lib/rails_erd/diagram/graphviz.rb:313:
warning: Passing safe_level with the 2nd argument of ERB.new is
deprecated. Do not use it, and specify other arguments as keyword
arguments.
/Users/koic/src/github.com/voormedia/rails-erd/lib/rails_erd/diagram/graphviz.rb:313:
warning: Passing trim_mode with the 3rd argument of ERB.new is
deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```
The interface of `ERB.new` will change from Ruby 2.6.
> Add :trim_mode and :eoutvar keyword arguments to ERB.new.
> Now non-keyword arguments other than first one are softly deprecated
> and will be removed when Ruby 2.5 becomes EOL. [Feature #14256] …

Deprecate safe_level of ERB.new in Ruby 2.6

---

lib/rails_erd/diagram.rb
test/unit/diagram_test.rb

Especially helpful when having polymorphic/indirect relationships

Removed restriction that allowed to exclude only models from a diagram

---

lib/rails_erd/domain/relationship.rb
test/unit/domain_test.rb
test/unit/graphviz_test.rb

By removing the identifier, we're removing duplicates but increasing the weight. 
Taking a look at the `rake examples` output for the "spree" application, we see that the `Address` model has:
```
has_many :billing_checkouts, :foreign_key => "bill_address_id", :class_name => "Checkout"
has_many :shipping_checkouts, :foreign_key => "ship_address_id", :class_name => "Checkout"
```
which, `<master>` generates (in `output/spree.dot`):
```
m_Address -> m_Checkout [arrowhead = "normal", arrowtail = "none", weight = "2"];
m_Address -> m_Checkout [arrowhead = "normal", arrowtail = "none", weight = "2"];
```
With this change, our output DOT shows this as:
```
m_Address -> m_Checkout [arrowhead = "normal", arrowtail = "none", weight = "4"];
```
I'm a bit nervous about this change; what I think I …

Remove identifier from association_identity

---

.travis.yml
gemfiles/Gemfile-rails.6.0.x
rails-erd.gemspec
test/test_helper.rb

Adds Rails 6 testing, but official support is still considered experimental until an official 6.0.0 release.

Add Rails 6 support

---

CHANGES.md
lib/rails_erd/version.rb

Release 1.6.0

---

.travis.yml
Gemfile
gemfiles/Gemfile-rails.6.1.x
lib/rails_erd/domain.rb
test/test_helper.rb
test/unit/attribute_test.rb

I'll be completely honest, this fix works, but I haven't spent the time to guarantee this is the "right" way to update this library for Rails 6.1 compatibility. Due to the way the tests fiddle with the innards of ActiveRecord, it seems like this library is only a few more major Rails releases away from needing its tests rewritten.
I saw the comments on https://github.com/voormedia/rails-erd/pull/345 by @gee-forr and several others, hopefully I'll be able to get the tests in travis happy if/when they fail.

Rails 6.1 Compatibility

---

lib/rails_erd/tasks.rake

This PR is intended to fix https://github.com/voormedia/rails-erd/issues/372
Now helper `say` is hidden in the module and not polluting the global scope

Avoid global scope polluting by helper 

---

lib/rails_erd/cli.rb

This environment file is the only thing that makes it impossible to use rails-erd with an
application which uses ActiveRecord but is not a Rails application. Since the objective of
loading that file is to eager-load the models, we can proceed without having loaded it - as
long as the user is aware.

Make loading environment.rb optional

---

lib/rails_erd/tasks.rake

Very small fix, but useful (at least for me).
This allow IDE to detect that we have a filepath (allowing devs to open
the file from the IDE directly).

Change task output for filename

---

.github/workflows/test.yml

Life is easier with smoothly running CI. I have ported CI to use GitHub Actions. For now, I have introduced only supported Ruby and Rails versions.
If welcomed, I can contribute to new version supporting only those (do some cleanups in code and README.md) and we can cut new major release.
Otherwise I can try to port older versions to CI as well.
Other possible improvement is to move Rails edge CI to weekly build, ping me if that would be welcomed as well.
PS: You can see CI in action at https://github.com/RubyElders/rails-erd/pull/1.

Introduce GitHub Actions.

---

README.md

This PR replaces the CI status badge from Travis CI to GitHub Actions.
I wanted to remove `.travis.yml` and gemfiles that are no longer used,
but it seems that #387 is in process, so I left it as is.

Replace CI badge from Travis to GH Actions

---

lib/rails_erd/domain.rb
test/unit/domain_test.rb

Closes https://github.com/voormedia/rails-erd/issues/389
Please note this approach still allows users to specify the Rails models if they want to see them on their graph, it just doesn't complain if the Rails generator has not been run and tables created.

Supress warnings for tableless Rails models

---

README.md

according to the docs: https://voormedia.github.io/rails-erd/customise.html, this should be plural

Fix example erdconfig foreign_keys

---

examples/generate.rb
lib/rails_erd.rb
lib/rails_erd/cli.rb
lib/rails_erd/config.rb
lib/rails_erd/diagram/mermaid.rb
lib/rails_erd/tasks.rake
test/unit/mermaid_test.rb
test/unit/rake_task_test.rb

Regarding https://github.com/voormedia/rails-erd/issues/226. This PR adds support for generating diagrams using [Mermaid](https://mermaid.js.org/).
here is an example for [Event Forms](https://github.com/krames/rails-erd/tree/master/examples/applications/event_forms) sample schema.
```mermaid
classDiagram
direction RL
class `ActiveRecord::InternalMetadata`
`ActiveRecord::InternalMetadata` : +string value
class `ActiveRecord::SchemaMigration`
class `Event`
`Event` : +boolean active
`Event` : +string costs
`Event` : +text description
`Event` : +string duration
`Event` : +text introduction
`Event` : +text report
`Event` : +string speaker
`Event` : +string target_audience
`Event` : +string title
`Event` : +string tutors
class `EventDate`
`EventDate` : +string date
`EventDate` : +text …
```

add Mermaid support
