voormedia/rails-erd

README.md

Submitted new PR with the clarified explanation the Rails ERD now supports Rails 3.0 - 4.2.

Update README.md to show Rails 3.0-4.2 support.

---

README.md
examples/erdconfig.example
lib/rails_erd.rb
lib/rails_erd/domain/attribute.rb
test/unit/attribute_test.rb

Provide `sort` option to keep attributes original order

---

CHANGES.md
lib/rails_erd/version.rb

Update to 1.4.0

---

test/test_helper.rb

Prevent deprecation warning by specifying test order

---

CHANGES.md
lib/rails_erd/version.rb

Bump to 1.4.1

---

lib/rails_erd/cli.rb

Choice's default values wipe values of configurations.
This enables .erdconfig

#150 Remove default value for choice

---

Gemfile
gemfiles/Gemfile-rails.3.2.x
gemfiles/Gemfile-rails.4.0.x
gemfiles/Gemfile-rails.4.1.x
gemfiles/Gemfile-rails.4.2.x
gemfiles/Gemfile-rails.edge
test/test_helper.rb
test/unit/graphviz_test.rb
test/unit/rake_task_test.rb

This seems to cause an issue on Travis primarily, some kind of race condition around the file creation and then testing for the file to exist.
#132

Remove creation of output files from test cycle

---

lib/generators/erd/templates/auto_generate_diagram.rake
lib/rails_erd.rb
lib/rails_erd/engine.rb

make RailsERD Engine, `auto generate diagram` feature now working.

make RailsERD Engine

---

CHANGES.md
lib/rails_erd/version.rb

Bump version number to 1.4.5 for release

---

lib/rails_erd/config.rb
lib/rails_erd/diagram.rb

This patch eliminates some Ruby warnings.

⚠️ Ruby Warnings

---

lib/rails_erd/diagram.rb

Did not work on my configuration without that
Ruby 2.3.0 
Rails 4.2.5

added .present? predicate to arrays

---

Gemfile

Redirect http://rubygems.org -> https://rubygems.org

Change rubygems source to https in Gemfile

---

lib/rails_erd/domain/entity.rb
test/unit/entity_test.rb

I discovered this bug will trying out the new `--cluster` option

Ml fix entity namespace

---

lib/rails_erd/cli.rb
lib/rails_erd/tasks.rake

config.eager_load_namespaces is only available in Rails4

---

README.md

This will keep it out of production/test environments.

Add more specific Gemfile installation instructions

---

lib/rails_erd/diagram/graphviz.rb

This PR is referencing to #274 and adding some default styling for clusters.

Refs #274, add margin to cluster

---

README.md

Remove require:false in installation instructions

---

.travis.yml

Bundler 2.0 is out and breaking some Travis commands

add update of rubygems

---

lib/rails_erd/domain.rb
rails-erd.gemspec
test/test_helper.rb

Rebase of #304 - Handle paper_trail's custom version classes.

---

lib/rails_erd/cli.rb
lib/rails_erd/config.rb
test/unit/config_test.rb

Rebase of #275 -- there was enough drift that I wanted to be extra careful, without making the original authors have to do extra work.
Thanks @danielevans for the original PR!

Allow extra config files to be listed via cli

---

lib/rails_erd/tasks.rake
test/unit/rake_task_test.rb

Rebase of #300 -- we had too much drift in the rake tasks for a clean merge.

Fix for bug when parameter to only option is a single model

---

CHANGES.md
lib/rails_erd/version.rb

Bump version and add changelog for v1.6.1

---

.travis.yml
gemfiles/Gemfile-rails.7.0.x
gemfiles/Gemfile-rails.edge
lib/rails_erd/domain/specialization.rb
test/test_helper.rb

This PR does the following:
* Adds support for Ruby 3
* Adds support for Rails 7
* Fixes Rails edge source
Note that these changes successfully update the gem, however, it does not update the example models.

Add Ruby 3 and Rails 7 support

---

lib/rails_erd/cli.rb

Fix spelling error

---

examples/generate.rb

Hande deprecated direct_descendants

---

lib/rails_erd/domain/attribute.rb

Rebasing #361 to pick up new checks

Map foreign keys & current column name to symbols
